### ISSUE TITLE
Does the iOS sdk support processing payments?

### ISSUE THREAD

**Issue by AtheistP3ace** [clover/clover-ios-sdk#10]
Title says it all. Looking to write an application for a merchant that use your POS system. They want a custom app so was hoping this SDK had everything needed to handle payment processing. Tell me its so! Would hate to have to implement all the REST API stuff manually.

**Comment by rkelly2001** [comment]
@AtheistP3ace what did you end up implementing.  I'm facing the same situation..

**Comment by eric-clover** [comment]
Please see the v1.0 update just released for examples of how to process payments as a merchant.  Credit card information can be collected using the iFrame integration, submitted for tokenization, and then that token can be used to process a payment.
