### ISSUE TITLE
Update Swift to 3.2 or higher?

### ISSUE THREAD

**Issue by AdamBCo** [clover/clover-ios-sdk#13]
@arjand @yusuferisen Are there any plans to update the version of Swift to 3.2 or higher?

**Comment by arjand** [comment]
At this time, not to my knowledge. I'll speak with the team and see if we can get it on the roadmap.

**Comment by uknowmeright** [comment]
Any update on this?

**Comment by dxcook5** [comment]
@uknowmeright, I couldn't find anything on our roadmap about this SDK.

**Comment by eric-clover** [comment]
I just pushed a v1.0 update to this repo that updates to the latest Swift, iOS, and models.  It also provides an iFrame integration for securely collecting credit card information.  it is a complete rewrite of the existing code, but with the changes it will be much easier to maintain moving forward.
